### ISSUE TITLE
parse error 

### ISSUE THREAD

**Issue by azarmadr** [fabianschuiki/llhd-sim#7]
Parse error at line: 1, column: 15
Unexpected `-`
Expected `(`

**Comment by fabianschuiki** [comment]
Good catch. The LLHD dependency needs updating -- it's pretty outdated here. Created #8 for that.

**Comment by fabianschuiki** [comment]
Should be fixed in the implementation within LLHD.

This repository is now deprecated in favor of the implementation within LLHD. Tracking continues there.
