### ISSUE TITLE
Update to llhd 0.13

### ISSUE THREAD

**Issue by fabianschuiki** [fabianschuiki/llhd-sim#8]

**Comment by azarmadr** [comment]
will you be starting this enhancement by changin toml file?

**Comment by azarmadr** [comment]
will you be starting this enhancement by changin toml file?

**Comment by fabianschuiki** [comment]
Yes indeed, but this will trigger *a lot* of errors due to significant updates in llhd :wink:

**Comment by azarmadr** [comment]
i will try then
i'm noob rustacian, but i have year xp in hdl

**Comment by fabianschuiki** [comment]
`llhd-sim` has now been merged into the LLHD repository for easier development and tracking of the IR. This also implicitly entailed and update to the most recent llhd version.

This repository is now deprecated in favor of the implementation within LLHD.
